### ISSUE TITLE
Release 1 Summary

### ISSUE THREAD

**Issue by heyhellomila** [milaroisin/atelier-xena#6]
Iteration 1
* [x] Setup Unity Project [#1]
* [x] Initial Environment Setup - CircleCI Integration [#3]
* [x] Update ReadMe File [#4]
* [x] Create Project Backlog [#5] 
* [x] Setup Github Labels and Documentation [#7]
* [x] Integrate Python Black [#15]

Iteration 2 and 3
* [ ] Setup the AI to Receive Audio Input [#17]
* [ ] Setup the AI to Receive Motion Input from the Headgear [#18]

Iteration 4
